version: '2.1'

services:

  postgres:
    image: postgres:10-alpine
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: books_shop
      POSTGRES_USER: badmin
      POSTGRES_PASSWORD: badminpass
#    volumes:
#      - './postgresql:/docker-entrypoint-initdb.d'
