###
POST http://localhost:8080/login
Content-Type: application/json

{
  "login": "admin",
  "password": "admin"
}

###
POST http://localhost:8080/login
Content-Type: application/json

{
  "login": "user",
  "password": "user"
}

