### admin
GET http://localhost:8080/whoami
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwYXZlbC5sYXphcmVua29AN2JpdHMuaXQiLCJpYXQiOjE2NDg3MjgyNjQsInN1YiI6ImFkbWluIiwiZXhwIjoxNjQ4NzMwMDY0LCJyb2xlcyI6WyJBRE1JTiIsIlVTRVIiXX0.BWedOrPc_r4OpaAzxF7D8N0RLCW_ed_o64PFDTZUJHQPtSuv8uej_OWl-GL2XIWw6_B09k2z60DtcX2WESYVGw

### user
GET http://localhost:8080/whoami
Authorization: Bearer eyJhbGciOiJIUzUxMiJ9.eyJpc3MiOiJwYXZlbC5sYXphcmVua29AN2JpdHMuaXQiLCJpYXQiOjE2NDg3MjgzNDgsInN1YiI6InVzZXIiLCJleHAiOjE2NDg3MzAxNDgsInJvbGVzIjpbIlVTRVIiXX0.c9vXSLk9TwklJkD-7H68wIiiVX9kVJVfIbZZEf7KZc9urd2OZwZ0h7d4WzBLWYYOBq7VcqBhIjJKvlJwdFy9Rg

### unauthorized
GET http://localhost:8080/whoami
